### ISSUE TITLE
Prompt for new Pin does not accept any keyboard input

### ISSUE THREAD

**Issue by AirBreak69** [token2/fido2-manage.ps1#1]
I am trying to initially setup a new Token2 T2F2-PIN+/Dual Release2.
As a very first step a PIN has to be set.
![grafik](https://github.com/token2/fido2-manage.ps1/assets/26233861/bb102ef5-da3d-44d3-9300-aa94432b4360)
Here **no keyboard input** or clipboard input is accepted. Only the return-key works, but this would lead to an empty PIN.
I tried _FIDO2.1 Manager.exe, fido2-manage.exe and fido2-manage.ps1 in powershell using administrative rights.
I did this on 3 different Win11 PCs and Labtops.

**Comment by token2** [comment]
We cannot replicate this behavior, but it seems like you might be referring to something else. The keyboard input is accepted, but it is not displayed in any form (no asterisks or other masked input). However, if you set a PIN by entering, for example, 695579 from your keyboard (even without seeing these digits), then hit Enter and confirm the same, the PIN will be set as expected.

**Comment by AirBreak69** [comment]
Before and finally, I managed the PIN setting using windows sign-in options.
In addition, I tried your "blind input" method - and it worked, too. So the keyboard input is not beeing displayed on my PC's.
Something special, you should investigate.
Thanks, so far.

**Comment by token2** [comment]
Hello, and thanks for confirming. In such case, this is rather a feature request and not an issue as such. We will close this issue and raise a request in the fido2-manage project (fido2-manage.ps1 is only its PowerShell wrapper).
